### PR TITLE
BLE prototype

### PR DESCRIPTION
**Pull request by sindney**
Hi, i created this BLE (Bluetooth Low Energy) API prototype, i'm not sure if it's useful? 

My intention was to provide this BLE device connection manager like interface, so users can script their own BLE data display page without worrying connection related problems. So they can just iterate the list of connected clients and do the real data transmit work with any client.

I'll implement pairing code related functions later and do more test to make sure there's no bugs.

What do you think? Any suggestions? 

Btw i got one question. I know i can call draw on headers and i can re-draw the area by name when data is updated (clock, battery etc). But is there a way to do this when i'm in a custom page and drawing with canvas apis (println etc)? Can i trigger the same re-draw tech to 'refresh' my page?

### CODE REVIEW

**Comment by sindney** [comment]
all

**Comment by ropg** [comment]
Wow... I'm impressed. I'll merge this when you're done testing some more, but this is very cool. This is exactly the way M5ez is supposed to make programming simpler.

I'd like to spend time with you thinking about how to further develop M5ez. Could you drop me a mail at rop ~at~ gonggri.jp ?

**Comment by ropg** [comment]
As for your question, if I recall correctly you can call redraws on header elements from wherever you want.

**Comment by sindney** [comment]
> 
> 
> Wow... I'm impressed. I'll merge this when you're done testing some more, but this is very cool. This is exactly the way M5ez is supposed to make programming simpler.
> 
> I'd like to spend time with you thinking about how to further develop M5ez. Could you drop me a mail at rop _at_ gonggri.jp ?

I just found a [bug](https://github.com/espressif/arduino-esp32/pull/3876) in arduino-esp32's BLE implementation. At first i thought it's my fault, my connected clients will all be disconnected if i disconnect just one of them. And i'v noticed that it's BLE implementation isn't very robust. I'm not sure if it's stable enough. 
Anyway, i just fixed some macro related issues, i'll commit them later. And i hope i can finish this BLE feature in this week, if i have enough free time 😅

**Comment by sindney** [comment]
Hi, ropg. I think the implementation is good enough now, i can't get the BLESecurity interface to work correctly and  i don't think it can :cry: I'v updated BLE related doc. You can review those code and docs now to consider if it's necessary to merge those code. I'll start to play with other sensors i bought :smile:.

**Comment by ropg** [comment]
Yay... Will have a look tonight and merge. Might add a sentence or two to the docs or something...

**Comment by ropg** [comment]
Sorry that took a while. A lot has happened meanwhile.

**Comment by sindney** [comment]
> Sorry that took a while. A lot has happened meanwhile.

It' ok, i wish you the best of health and success.

**Pull request merged**
