### PR TITLE
Move sysinfo example to its own folder

### PR DESCRIPTION
**Pull request by per1234**
The Arduino IDE opens all files from a sketch folder as tabs of one project. So multiple sketches in the same folder causes compilation to fail with "redefinition of" errors.

### CODE REVIEW

**Comment by ropg** [comment]
The point here is explicitly that the same `sysinfo,ino` file can be used a a sub-menu of the demo program as well as stand-alone. That's what the MAIN_DECLARED define is for, it makes sure the setup() and loop() are only defined once. See the [documentation on this](https://github.com/ropg/M5ez#dual-use-sketches). Did you run into actual compile problems or did you just see two .ino's in the same directory and figure that must be wrong?

**Comment by per1234** [comment]
Sorry, I didn't see that. It was detected as part of an automated scan.

**Comment by ropg** [comment]
> Sorry, I didn't see that. It was detected as part of an automated scan.

Ah, OK.

Is this not going to recur? Can you whitelist? 


Rop

**Comment by per1234** [comment]
I do try to check for duplicate PRs but, to be sure, I've blacklisted this repository from any future scans.

**Comment by ropg** [comment]
> I do try to check for duplicate PRs but, to be sure, I've blacklisted this repository from any future scans.

tnx.


Rop

**Pull request closed without merging**
