### PR TITLE
add battery info to ezHeader

### PR DESCRIPTION
**Pull request by sindney**
getBatteryLevel() function copied from https://github.com/m5stack/M5Stack/issues/74

### CODE REVIEW

**Comment by ropg** [comment]
Wow. Very, very cool! Will gladly roll a new version with this... (It would need documentation then too...)

I've been out of M5 things for too long, so help me out here. This is with the standard M5Stack bottom now? How many people have a battery that can report like this?

**Comment by sindney** [comment]
> 
> 
> Wow. Very, very cool! Will gladly roll a new version with this... (It would need documentation then too...)
> 
> I've been out of M5 things for too long, so help me out here. This is with the standard M5Stack bottom now? How many people have a battery that can report like this?

Ok, i'll complete the doc, and create some settings with this feature and turn this off like the clock feature by default. I'm using M5Stack Gray(board manufactured in 2018.3), the standard case can report battery levels too(i have another 500mha back with mic), but the report is not very accurate (only 4 levels)

**Comment by ropg** [comment]
Still, better than one level... Thanks. I will release a new version after you document..

**Comment by sindney** [comment]
> 
> 
> Still, better than one level... Thanks. I will release a new version after you document..

Docs are done. Btw, i still have 2 days of free time to code something. I'm interested in using blue-tooth to transmit some data from pc to M5Stack, so it can act as a 'PC status Monitor' to show something like CPU temperature or frequency or something like that. I may make more PRs later if everything goes well :smile:  You may want to release new versions later. I'll let you know if i'm not able to make more PRs. :handshake:

**Comment by ropg** [comment]
Just did. Can always release a newer one again in a few days... I'd be happy to see what else you come up with... You seem quite proficient in understanding how M5ez works... :)

**Pull request merged**
