### PR TITLE
Improve stability and line wrapping(Tested only under Linux without FACES)

### PR DESCRIPTION
**Pull request by EternityForest**
I believe, but am not certain, that I have discovered and fixed a few bugs here:
I haven't tested with \r line endings or FACES(Because I don't have it!), so I may have introduced new bugs, but as I see it, this code fixes:

* Support /n line endings
* No crash with textbox and empty string
* Properly handle the last line in multiline boxes

Thanks!

### CODE REVIEW

**Comment by EternityForest** [comment]
Or... Maybe not. I'm still running into cases where newlines seem to be ignored, although it seems better than before and fixes a crash I was having.

**Comment by ropg** [comment]
M5ez was my first ever Arduino library and my first ever project in C/C++. I've only coded in LUA, Python and PHP before. And now that I've done [ezTime](https://github.com/ropg/ezTime) and have a little more experience, I can see some spots where more simplicity and readability is in order.

Of all the code in M5ez, I'm most unhappy with textBox and the way it is currently written. Some of it will need to be redone. There is some bigger work to be done in general: I would like to give header, canvas and buttons their own objects and create a mechanism to ask for a section of the header for header widgets and register a function to redraw that part (internally for clock and wifi signal indicator, but also to be available to user code).

I'll test with your code soon and merge it if it works for me too, but it's really only a stopgap measure: textBox needs work.

**Comment by EternityForest** [comment]
In general it seems like an excellent library! I'm using it for my Squirrel language port project and it's been great so far.

I'll probably have a few more PRs in the future(I'm working on dynamic theme selection and slight power saving by dimming the screen).

**Comment by ropg** [comment]
> In general it seems like an excellent library! I'm using it for my Squirrel language port project and it's been great so far.
> 
> I'll probably have a few more PRs in the future(I'm working on dynamic theme selection and slight power saving by dimming the screen).


There will be a "settings" menu soon that will have an item for the wifi menu, backlight brightness setting, header-bar clock settings (on/off, timezone, 12/24 hr, etc), FACES on/off and whatever else we can think of, it might as well have a theme selector...

**Comment by EternityForest** [comment]
Oh that would be cool, to actually select the theme from the interface.

What I've done is just added a class called EzTheme, so you can set the
theme attributes via ez.theme.THEMEATTR, or just replace the theme object
entirely by assigning another theme class.

On vaugely related matters:

I ran into some trouble with the M5 powering off after 30S if you turn the
brightness down too much (They just use a power bank type chip), so you
might want to watch for that.


You might be able to detect FACES just by scanning the I2C bus and looking
for the addresses they use. That might cause a problem if a different
device with the same address was connected, but it might be fine in
practice.

**Comment by ropg** [comment]
> Oh that would be cool, to actually select the theme from the interface.
> 
> What I've done is just added a class called EzTheme, so you can set the
> theme attributes via ez.theme.THEMEATTR, or just replace the theme object
> entirely by assigning another theme class.

Was just thinking about themes, but is not completely uncomplicated: you would want the programmer to select themes that at least work with what is actually being displayed, and possibly without adding too much code and/or stored data that almost never gets used. Maybe the actual theme in use could be a pointer to a class, so it can be changed on the fly. Maybe themes can just extend the default theme class so they only need to implement what they need to change... I'll give it a further think as I create more classes anyway (for header, canvas and buttons). (I plan to make the canvas an extension to the Print class and store what has been printed with font, color and position so text can scroll even if the display doesn't let me read back the contents. And that way I even have a scroll-back buffer...)

At some point I'll get to a "future plans" file in the repo somewhere...


> On vaguely related matters:
> 
> I ran into some trouble with the M5 powering off after 30S if you turn the
> brightness down too much (They just use a power bank type chip), so you
> might want to watch for that.

Noted, thanks... (I wonder if that only happens on battery power.)


> You might be able to detect FACES just by scanning the I2C bus and looking
> for the addresses they use. That might cause a problem if a different
> device with the same address was connected, but it might be fine in
> practice.

I tried that but it doesn't show up with the usual scanning method (forget what that was, but none of the I2C scanner sketches show it, IIRC.

**Comment by EternityForest** [comment]
Yeah, it's only on battery power. I've heard the FIRE version has some
special i2c command to make it not shut down.

Resource usage is a bit of an issue with dynamic themes... C++ doesn't seem
to really have a lot of easy ways to do it, besides just having a data
class of variables and hoping GCC optimizes it, or that it doesn't matter
because we have the 4MB psram.

I like the pointer to class idea. I had gotten it working with just a theme
directly as a member, but the instant switching of pointers is cool.

If you used a pointer to a class, you could ensure that the default theme
class was instantiated in PSRAM no matter what IDE settings were used, and
storage space probably isn't a big issue there.

You could have an ez.begin that accepts a pointer to a theme, so that if
you never use the default theme it never gets instantiated and the compiler
hopefully doesn't include it.

**Comment by ropg** [comment]
I have incorporated (and slightly modified) your textBox modification. As you can see we now have dynamic themes and a theme chooser. Please give it all a go and let me know if you see any remaining problems...

**Pull request closed without merging**
